services:
  mongodb:
    image: mongo:8.0

    container_name: mongodb

    ports:
      - "27007:27017"

    volumes:
      - mongodata:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    networks:
      - backend

    restart: always

  postgres:
    image: pgvector/pgvector:0.8.5-pg18-trixie
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongodata:
  postgresdata:
    