from enum import Enum

class ResponseStatus(Enum):
    PROJECT_NOT_FOUND = "Project not found."
    File_Type_Not_Supported = "File type not supported."
    File_Size_Exceeded = "File size exceeds the limit."
    File_Validation_Success = "File is valid."
    File_Upload_Success = "File uploaded successfully."
    File_Processed_Success = "File processed successfully."
    File_processing_failed = "Failed to process file content."
    File_delete_success = "File deleted successfully."
    File_Upload_Failed = "Failed to upload file."
    No_Chunks_Found = "No chunks found for the given project."
    File_Not_Found = "File not found."
    FAILED_TO_INSERT_CHUNKS = "Failed to insert data chunks into vector database."
    SUCCESSFULLY_INSERTED_CHUNKS = "Successfully inserted data chunks into vector database."
    COLLECTION_NOT_FOUND = "Collection not found in vector database."
    COLLECTION_IS_FOUND = "Collection found in vector database."
    RAG_ANSWER_GENERATED = "Successfully generated answer using RAG."
    RAG_ANSWER_GENERATION_FAILED = "Failed to generate answer using RAG."